version: '2'
services:
  sftp:
    build: ./sftp-server
    ports:
     - "3022:22"
    volumes:
     - /tmp:/home/jetbrains/upload
     - ~/.ssh/id_rsa.pub:/home/jetbrains/.ssh/keys/id_rsa.pub:ro
    command: jetbrains:jetbrains:1001
  sftp-no-password:
    build: ./sftp-server-no-password
    ports:
      - "4022:22"
    volumes:
      - /tmp:/home/jetbrains/upload
    command: jetbrains:1001
  webserver:
    build: ./php-71-apache-xdebug
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=192.168.2.108
  mysql:
      build: ./mysql
      ports:
        - "33306:3306"
      volumes:
        - ./data:/var/lib/mysql
  ftp:
    build: ./ftp
    volumes:
      - /tmp:/home/virtual/jetbrains/share
    environment:
      PASV_ADDRESS: 192.168.2.186
      VSFTPD_USER_1: "jetbrains:jetbrains::"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  ftps:
    build: ./ftps
    volumes:
          - /tmp:/home/virtual/jetbrains/share
    environment:
    #change the line below with your IP address
      PASV_ADDRESS: 192.168.2.108
      VSFTPD_USER_1: "jetbrains:jetbrains::"
      PASV_MIN_PORT: 30010
      PASV_MAX_PORT: 30019
    ports:
      - "23:21"
      - "30010-30019:30010-30019"
  pure-ftpd:
    build: ./pure-ftpd
    volumes:
      - /tmp:/home/ftpusers/jetbrains/
    ports:
      - "24:21"
      - "30020-30029:30020-30029"
    environment:
      #change the line below with your IP address
      PASV_ADDRESS: 192.168.2.118
  pro-ftpd:
      build:
        context: ./proftpd
        args:
          #change the line below with your IP address
          PASV_ADDRESS: 192.168.2.118
      volumes:
        - /tmp:/home/FTP-shared
      ports:
        - "25:21"
        - "30040-30049:30040-30049"
      extra_hosts:
       - "moby:127.0.0.1"

